Fix a bug where a RAII object was created for just one line instead of a block.
Found by clang:

../../third_party/webrtc/video_engine/vie_render_manager.cc:157:3: error: expression result unused [-Werror,-Wunused-value]
  ViEManagerWriteScoped(*this);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Review URL: https://webrtc-codereview.appspot.com/599005